CREATE TABLE PAYMENT (
  ID SERIAL  PRIMARY KEY  NOT NULL,
  SOURCE_ACC_ID bigint NOT NULL,
  DEST_ACC_ID bigint NOT NULL,
  AMOUNT float NULL,
  REASON varchar(50)  NULL,
  PAYMENT_STATUS boolean NOT NULL,
  DATE_CREATED timestamp NULL
)
